/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesUiUxWeb3MarketingRouteImport } from './routes/services/ui-ux-web3-marketing'
import { Route as ServicesImmersiveVrarmrRouteImport } from './routes/services/immersive-vrarmr'
import { Route as ServicesEmergingTechAiRouteImport } from './routes/services/emerging-tech-ai'
import { Route as ServicesCustomSoftwareSaasRouteImport } from './routes/services/custom-software-saas'
import { Route as ServicesCloudDevopsRouteImport } from './routes/services/cloud-devops'
import { Route as ServicesBlockchainWeb3RouteImport } from './routes/services/blockchain-web3'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUiUxWeb3MarketingRoute =
  ServicesUiUxWeb3MarketingRouteImport.update({
    id: '/ui-ux-web3-marketing',
    path: '/ui-ux-web3-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesImmersiveVrarmrRoute = ServicesImmersiveVrarmrRouteImport.update({
  id: '/immersive-vrarmr',
  path: '/immersive-vrarmr',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEmergingTechAiRoute = ServicesEmergingTechAiRouteImport.update({
  id: '/emerging-tech-ai',
  path: '/emerging-tech-ai',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomSoftwareSaasRoute =
  ServicesCustomSoftwareSaasRouteImport.update({
    id: '/custom-software-saas',
    path: '/custom-software-saas',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCloudDevopsRoute = ServicesCloudDevopsRouteImport.update({
  id: '/cloud-devops',
  path: '/cloud-devops',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBlockchainWeb3Route = ServicesBlockchainWeb3RouteImport.update({
  id: '/blockchain-web3',
  path: '/blockchain-web3',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/blockchain-web3': typeof ServicesBlockchainWeb3Route
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/custom-software-saas': typeof ServicesCustomSoftwareSaasRoute
  '/services/emerging-tech-ai': typeof ServicesEmergingTechAiRoute
  '/services/immersive-vrarmr': typeof ServicesImmersiveVrarmrRoute
  '/services/ui-ux-web3-marketing': typeof ServicesUiUxWeb3MarketingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/blockchain-web3': typeof ServicesBlockchainWeb3Route
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/custom-software-saas': typeof ServicesCustomSoftwareSaasRoute
  '/services/emerging-tech-ai': typeof ServicesEmergingTechAiRoute
  '/services/immersive-vrarmr': typeof ServicesImmersiveVrarmrRoute
  '/services/ui-ux-web3-marketing': typeof ServicesUiUxWeb3MarketingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/blockchain-web3': typeof ServicesBlockchainWeb3Route
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/custom-software-saas': typeof ServicesCustomSoftwareSaasRoute
  '/services/emerging-tech-ai': typeof ServicesEmergingTechAiRoute
  '/services/immersive-vrarmr': typeof ServicesImmersiveVrarmrRoute
  '/services/ui-ux-web3-marketing': typeof ServicesUiUxWeb3MarketingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/services/$slug'
    | '/services/blockchain-web3'
    | '/services/cloud-devops'
    | '/services/custom-software-saas'
    | '/services/emerging-tech-ai'
    | '/services/immersive-vrarmr'
    | '/services/ui-ux-web3-marketing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/services/$slug'
    | '/services/blockchain-web3'
    | '/services/cloud-devops'
    | '/services/custom-software-saas'
    | '/services/emerging-tech-ai'
    | '/services/immersive-vrarmr'
    | '/services/ui-ux-web3-marketing'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/services/$slug'
    | '/services/blockchain-web3'
    | '/services/cloud-devops'
    | '/services/custom-software-saas'
    | '/services/emerging-tech-ai'
    | '/services/immersive-vrarmr'
    | '/services/ui-ux-web3-marketing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ui-ux-web3-marketing': {
      id: '/services/ui-ux-web3-marketing'
      path: '/ui-ux-web3-marketing'
      fullPath: '/services/ui-ux-web3-marketing'
      preLoaderRoute: typeof ServicesUiUxWeb3MarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/immersive-vrarmr': {
      id: '/services/immersive-vrarmr'
      path: '/immersive-vrarmr'
      fullPath: '/services/immersive-vrarmr'
      preLoaderRoute: typeof ServicesImmersiveVrarmrRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/emerging-tech-ai': {
      id: '/services/emerging-tech-ai'
      path: '/emerging-tech-ai'
      fullPath: '/services/emerging-tech-ai'
      preLoaderRoute: typeof ServicesEmergingTechAiRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-software-saas': {
      id: '/services/custom-software-saas'
      path: '/custom-software-saas'
      fullPath: '/services/custom-software-saas'
      preLoaderRoute: typeof ServicesCustomSoftwareSaasRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-devops': {
      id: '/services/cloud-devops'
      path: '/cloud-devops'
      fullPath: '/services/cloud-devops'
      preLoaderRoute: typeof ServicesCloudDevopsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/blockchain-web3': {
      id: '/services/blockchain-web3'
      path: '/blockchain-web3'
      fullPath: '/services/blockchain-web3'
      preLoaderRoute: typeof ServicesBlockchainWeb3RouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesBlockchainWeb3Route: typeof ServicesBlockchainWeb3Route
  ServicesCloudDevopsRoute: typeof ServicesCloudDevopsRoute
  ServicesCustomSoftwareSaasRoute: typeof ServicesCustomSoftwareSaasRoute
  ServicesEmergingTechAiRoute: typeof ServicesEmergingTechAiRoute
  ServicesImmersiveVrarmrRoute: typeof ServicesImmersiveVrarmrRoute
  ServicesUiUxWeb3MarketingRoute: typeof ServicesUiUxWeb3MarketingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesBlockchainWeb3Route: ServicesBlockchainWeb3Route,
  ServicesCloudDevopsRoute: ServicesCloudDevopsRoute,
  ServicesCustomSoftwareSaasRoute: ServicesCustomSoftwareSaasRoute,
  ServicesEmergingTechAiRoute: ServicesEmergingTechAiRoute,
  ServicesImmersiveVrarmrRoute: ServicesImmersiveVrarmrRoute,
  ServicesUiUxWeb3MarketingRoute: ServicesUiUxWeb3MarketingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
